name: free_play
description: Free to Play Game Database

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  pmvvm: ^4.0.1
  carousel_slider: ^4.1.1
  http: ^0.13.4
  toast: ^0.2.9
  google_fonts: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/logo/
    - assets/icons/
